version: '3'
services:
  doeidoso:
    build: .
    command: npm run start
    ports:
      - "3001:3000"
    volumes:
      - .:/scheduling-simulator-react
  doeidoso-ui:
    container_name: doeidoso-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/scheduling-simulator-react'
    ports:
      - '9009:9009'
    environment:
      - NODE_ENV=development
    depends_on:
      - doeidoso
    command: npm run storybook
