export const SIMULATOR_ADD_INFO = 'SIMULATOR_ADD_INFO' 
export const SIMULATOR_RESET_INFO = 'SIMULATOR_RESET_INFO' 

export const CORE_ADD_LIST = 'CORE_ADD_LIST' 

export const PROCESS_ADD_LIST = 'PROCESS_ADD_LIST' 
